import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

// Build a markdown string from the exportSummary payload
function buildMarkdown(s) {
  const lines = [];
  lines.push(`# ${s.header}`);
  lines.push('');
  lines.push(`**${s.verdictLine}**`);
  lines.push('');

  lines.push('## Dimension Highlights');
  (s.dimensionHighlights || []).forEach(d => lines.push(`- ${d}`));
  lines.push('');

  if (s.criticalGaps?.length) {
    lines.push('## Critical Gaps');
    s.criticalGaps.forEach(g => lines.push(`- ${g}`));
    lines.push('');
  }

  if (s.talkingPointsHighlights?.length) {
    lines.push('## Key Talking Points');
    s.talkingPointsHighlights.forEach(t => lines.push(`- ${t}`));
    lines.push('');
  }

  if (s.goals?.length) {
    lines.push('## Development Goals');
    s.goals.forEach((g, i) => lines.push(`${i + 1}. ${g}`));
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Generated by GCSP Lead Advisor · ${new Date().toLocaleDateString()}_`);
  return lines.join('\n');
}

function downloadMd(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function Export({ analysisResult, onReset }) {
  const [exported, setExported] = useState(false);
  const navigate = useNavigate();

  if (!analysisResult) {
    return (
      <div style={{ textAlign: 'center', padding: '4rem 2rem', color: '#747480' }}>
        <p style={{ fontSize: '1.125rem', marginBottom: '1rem' }}>No analysis available to export yet.</p>
        <button
          onClick={() => navigate('/')}
          style={{ padding: '0.65rem 1.75rem', background: '#FFE600', color: '#1A1A24',
            border: 'none', borderRadius: '2px', cursor: 'pointer', fontWeight: '700', fontSize: '0.9375rem' }}
        >
          &larr; Go to Input
        </button>
      </div>
    );
  }

  const summary  = analysisResult.exportSummary || {};
  const gcspName = summary.header?.replace('GCSP Review Summary \u2014 ', '') ?? 'GCSP';

  const handleExport = () => {
    const md       = buildMarkdown(summary);
    const filename = `${gcspName.replace(/\s+/g, '_')}_Review_Summary.md`;
    downloadMd(filename, md);
    setExported(true);
  };

  const handleStartNew = () => {
    onReset();
    navigate('/');
  };

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.75rem', fontWeight: '700', color: '#2E2E38', margin: 0, letterSpacing: '-0.01em' }}>Export</h1>
        <p style={{ color: '#747480', marginTop: '0.4rem', fontSize: '0.9375rem' }}>
          Download a summary of the calibration review for <strong style={{ color: '#2E2E38' }}>{gcspName}</strong>.
        </p>
      </div>

      {/* Preview card */}
      <div style={{ background: '#fff', border: '1px solid #D7D7DC',
        borderLeft: '4px solid #FFE600',
        borderRadius: '2px',
        padding: '1.5rem 1.75rem', marginBottom: '1.75rem',
        boxShadow: '0 2px 6px rgba(46,46,56,0.07)' }}>

        <p style={{ fontSize: '0.6875rem', fontWeight: '700', textTransform: 'uppercase',
          letterSpacing: '0.1em', color: '#747480', margin: '0 0 0.75rem' }}>Summary preview</p>

        <p style={{ fontWeight: '700', fontSize: '1rem', color: '#2E2E38', margin: '0 0 0.4rem' }}>
          {summary.header}
        </p>
        <p style={{ fontSize: '0.875rem', color: '#1558CC', fontWeight: '600', margin: '0 0 1.25rem' }}>
          {summary.verdictLine}
        </p>

        {summary.dimensionHighlights?.length > 0 && (
          <div style={{ marginBottom: '1rem' }}>
            <p style={{ fontSize: '0.75rem', fontWeight: '700', textTransform: 'uppercase',
              letterSpacing: '0.08em', color: '#747480', margin: '0 0 0.4rem' }}>Dimensions</p>
            <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.875rem',
              color: '#505060', lineHeight: '1.7' }}>
              {summary.dimensionHighlights.map((d, i) => <li key={i}>{d}</li>)}
            </ul>
          </div>
        )}

        {summary.criticalGaps?.length > 0 && (
          <div style={{ marginBottom: '1rem' }}>
            <p style={{ fontSize: '0.75rem', fontWeight: '700', textTransform: 'uppercase',
              letterSpacing: '0.08em', color: '#C4313A', margin: '0 0 0.4rem' }}>Critical Gaps</p>
            <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.875rem',
              color: '#7C2020', lineHeight: '1.7' }}>
              {summary.criticalGaps.map((g, i) => <li key={i}>{g}</li>)}
            </ul>
          </div>
        )}

        {summary.goals?.length > 0 && (
          <div>
            <p style={{ fontSize: '0.75rem', fontWeight: '700', textTransform: 'uppercase',
              letterSpacing: '0.08em', color: '#747480', margin: '0 0 0.4rem' }}>Goals</p>
            <ol style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.875rem',
              color: '#505060', lineHeight: '1.7' }}>
              {summary.goals.map((g, i) => <li key={i}>{g}</li>)}
            </ol>
          </div>
        )}
      </div>

      {/* Export button + confirmation */}
      {!exported ? (
        <button
          onClick={handleExport}
          style={{ display: 'block', width: '100%', padding: '1rem',
            background: '#FFE600', color: '#1A1A24', border: 'none',
            borderRadius: '2px', fontSize: '1.0625rem', fontWeight: '700',
            cursor: 'pointer', letterSpacing: '0.02em', fontFamily: 'inherit' }}
        >
          &#8595;&nbsp; Export Summary (.md)
        </button>
      ) : (
        <div style={{ background: '#E8F5EC', border: '1px solid #A3D8AF', borderRadius: '2px',
          padding: '1rem 1.25rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ fontSize: '1.25rem', color: '#168736' }}>&#10003;</span>
          <span style={{ fontWeight: '700', color: '#168736', fontSize: '0.9375rem' }}>
            Summary exported &mdash; file download started.
          </span>
        </div>
      )}

      {/* Navigation */}
      <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem',
        paddingTop: '1.5rem', borderTop: '1px solid #EBEBEF', flexWrap: 'wrap' }}>
        <button onClick={() => navigate('/analysis')}
          style={{ padding: '0.65rem 1.5rem', background: '#fff', color: '#2E2E38',
            border: '1px solid #2E2E38', borderRadius: '2px', fontSize: '0.9375rem',
            fontWeight: '600', cursor: 'pointer', fontFamily: 'inherit' }}>
          &larr; Back to Analysis
        </button>
        <button onClick={handleStartNew}
          style={{ padding: '0.65rem 1.75rem', background: '#2E2E38', color: '#fff',
            border: 'none', borderRadius: '2px', fontSize: '0.9375rem',
            fontWeight: '700', cursor: 'pointer', fontFamily: 'inherit' }}>
          &#8635;&nbsp; Start New
        </button>
      </div>
    </div>
  );
}
